
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DutyPeriod` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DutyPeriod
 * 
 */
export type DutyPeriodModel = runtime.Types.Result.DefaultSelection<Prisma.$DutyPeriodPayload>

export type AggregateDutyPeriod = {
  _count: DutyPeriodCountAggregateOutputType | null
  _min: DutyPeriodMinAggregateOutputType | null
  _max: DutyPeriodMaxAggregateOutputType | null
}

export type DutyPeriodMinAggregateOutputType = {
  id: string | null
  startDate: Date | null
  endDate: Date | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
  pharmacyId: string | null
}

export type DutyPeriodMaxAggregateOutputType = {
  id: string | null
  startDate: Date | null
  endDate: Date | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
  pharmacyId: string | null
}

export type DutyPeriodCountAggregateOutputType = {
  id: number
  startDate: number
  endDate: number
  notes: number
  createdAt: number
  updatedAt: number
  pharmacyId: number
  _all: number
}


export type DutyPeriodMinAggregateInputType = {
  id?: true
  startDate?: true
  endDate?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  pharmacyId?: true
}

export type DutyPeriodMaxAggregateInputType = {
  id?: true
  startDate?: true
  endDate?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  pharmacyId?: true
}

export type DutyPeriodCountAggregateInputType = {
  id?: true
  startDate?: true
  endDate?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  pharmacyId?: true
  _all?: true
}

export type DutyPeriodAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DutyPeriod to aggregate.
   */
  where?: Prisma.DutyPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DutyPeriods to fetch.
   */
  orderBy?: Prisma.DutyPeriodOrderByWithRelationInput | Prisma.DutyPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DutyPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DutyPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DutyPeriods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DutyPeriods
  **/
  _count?: true | DutyPeriodCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DutyPeriodMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DutyPeriodMaxAggregateInputType
}

export type GetDutyPeriodAggregateType<T extends DutyPeriodAggregateArgs> = {
      [P in keyof T & keyof AggregateDutyPeriod]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDutyPeriod[P]>
    : Prisma.GetScalarType<T[P], AggregateDutyPeriod[P]>
}




export type DutyPeriodGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DutyPeriodWhereInput
  orderBy?: Prisma.DutyPeriodOrderByWithAggregationInput | Prisma.DutyPeriodOrderByWithAggregationInput[]
  by: Prisma.DutyPeriodScalarFieldEnum[] | Prisma.DutyPeriodScalarFieldEnum
  having?: Prisma.DutyPeriodScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DutyPeriodCountAggregateInputType | true
  _min?: DutyPeriodMinAggregateInputType
  _max?: DutyPeriodMaxAggregateInputType
}

export type DutyPeriodGroupByOutputType = {
  id: string
  startDate: Date
  endDate: Date
  notes: string | null
  createdAt: Date
  updatedAt: Date
  pharmacyId: string
  _count: DutyPeriodCountAggregateOutputType | null
  _min: DutyPeriodMinAggregateOutputType | null
  _max: DutyPeriodMaxAggregateOutputType | null
}

type GetDutyPeriodGroupByPayload<T extends DutyPeriodGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DutyPeriodGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DutyPeriodGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DutyPeriodGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DutyPeriodGroupByOutputType[P]>
      }
    >
  >



export type DutyPeriodWhereInput = {
  AND?: Prisma.DutyPeriodWhereInput | Prisma.DutyPeriodWhereInput[]
  OR?: Prisma.DutyPeriodWhereInput[]
  NOT?: Prisma.DutyPeriodWhereInput | Prisma.DutyPeriodWhereInput[]
  id?: Prisma.StringFilter<"DutyPeriod"> | string
  startDate?: Prisma.DateTimeFilter<"DutyPeriod"> | Date | string
  endDate?: Prisma.DateTimeFilter<"DutyPeriod"> | Date | string
  notes?: Prisma.StringNullableFilter<"DutyPeriod"> | string | null
  createdAt?: Prisma.DateTimeFilter<"DutyPeriod"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DutyPeriod"> | Date | string
  pharmacyId?: Prisma.StringFilter<"DutyPeriod"> | string
  pharmacy?: Prisma.XOR<Prisma.PharmacyScalarRelationFilter, Prisma.PharmacyWhereInput>
}

export type DutyPeriodOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  pharmacyId?: Prisma.SortOrder
  pharmacy?: Prisma.PharmacyOrderByWithRelationInput
}

export type DutyPeriodWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DutyPeriodWhereInput | Prisma.DutyPeriodWhereInput[]
  OR?: Prisma.DutyPeriodWhereInput[]
  NOT?: Prisma.DutyPeriodWhereInput | Prisma.DutyPeriodWhereInput[]
  startDate?: Prisma.DateTimeFilter<"DutyPeriod"> | Date | string
  endDate?: Prisma.DateTimeFilter<"DutyPeriod"> | Date | string
  notes?: Prisma.StringNullableFilter<"DutyPeriod"> | string | null
  createdAt?: Prisma.DateTimeFilter<"DutyPeriod"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DutyPeriod"> | Date | string
  pharmacyId?: Prisma.StringFilter<"DutyPeriod"> | string
  pharmacy?: Prisma.XOR<Prisma.PharmacyScalarRelationFilter, Prisma.PharmacyWhereInput>
}, "id">

export type DutyPeriodOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  pharmacyId?: Prisma.SortOrder
  _count?: Prisma.DutyPeriodCountOrderByAggregateInput
  _max?: Prisma.DutyPeriodMaxOrderByAggregateInput
  _min?: Prisma.DutyPeriodMinOrderByAggregateInput
}

export type DutyPeriodScalarWhereWithAggregatesInput = {
  AND?: Prisma.DutyPeriodScalarWhereWithAggregatesInput | Prisma.DutyPeriodScalarWhereWithAggregatesInput[]
  OR?: Prisma.DutyPeriodScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DutyPeriodScalarWhereWithAggregatesInput | Prisma.DutyPeriodScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DutyPeriod"> | string
  startDate?: Prisma.DateTimeWithAggregatesFilter<"DutyPeriod"> | Date | string
  endDate?: Prisma.DateTimeWithAggregatesFilter<"DutyPeriod"> | Date | string
  notes?: Prisma.StringNullableWithAggregatesFilter<"DutyPeriod"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DutyPeriod"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"DutyPeriod"> | Date | string
  pharmacyId?: Prisma.StringWithAggregatesFilter<"DutyPeriod"> | string
}

export type DutyPeriodCreateInput = {
  id?: string
  startDate: Date | string
  endDate: Date | string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  pharmacy: Prisma.PharmacyCreateNestedOneWithoutDutyPeriodsInput
}

export type DutyPeriodUncheckedCreateInput = {
  id?: string
  startDate: Date | string
  endDate: Date | string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  pharmacyId: string
}

export type DutyPeriodUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pharmacy?: Prisma.PharmacyUpdateOneRequiredWithoutDutyPeriodsNestedInput
}

export type DutyPeriodUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pharmacyId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DutyPeriodCreateManyInput = {
  id?: string
  startDate: Date | string
  endDate: Date | string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  pharmacyId: string
}

export type DutyPeriodUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DutyPeriodUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pharmacyId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DutyPeriodListRelationFilter = {
  every?: Prisma.DutyPeriodWhereInput
  some?: Prisma.DutyPeriodWhereInput
  none?: Prisma.DutyPeriodWhereInput
}

export type DutyPeriodOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DutyPeriodCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  pharmacyId?: Prisma.SortOrder
}

export type DutyPeriodMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  pharmacyId?: Prisma.SortOrder
}

export type DutyPeriodMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  pharmacyId?: Prisma.SortOrder
}

export type DutyPeriodCreateNestedManyWithoutPharmacyInput = {
  create?: Prisma.XOR<Prisma.DutyPeriodCreateWithoutPharmacyInput, Prisma.DutyPeriodUncheckedCreateWithoutPharmacyInput> | Prisma.DutyPeriodCreateWithoutPharmacyInput[] | Prisma.DutyPeriodUncheckedCreateWithoutPharmacyInput[]
  connectOrCreate?: Prisma.DutyPeriodCreateOrConnectWithoutPharmacyInput | Prisma.DutyPeriodCreateOrConnectWithoutPharmacyInput[]
  createMany?: Prisma.DutyPeriodCreateManyPharmacyInputEnvelope
  connect?: Prisma.DutyPeriodWhereUniqueInput | Prisma.DutyPeriodWhereUniqueInput[]
}

export type DutyPeriodUncheckedCreateNestedManyWithoutPharmacyInput = {
  create?: Prisma.XOR<Prisma.DutyPeriodCreateWithoutPharmacyInput, Prisma.DutyPeriodUncheckedCreateWithoutPharmacyInput> | Prisma.DutyPeriodCreateWithoutPharmacyInput[] | Prisma.DutyPeriodUncheckedCreateWithoutPharmacyInput[]
  connectOrCreate?: Prisma.DutyPeriodCreateOrConnectWithoutPharmacyInput | Prisma.DutyPeriodCreateOrConnectWithoutPharmacyInput[]
  createMany?: Prisma.DutyPeriodCreateManyPharmacyInputEnvelope
  connect?: Prisma.DutyPeriodWhereUniqueInput | Prisma.DutyPeriodWhereUniqueInput[]
}

export type DutyPeriodUpdateManyWithoutPharmacyNestedInput = {
  create?: Prisma.XOR<Prisma.DutyPeriodCreateWithoutPharmacyInput, Prisma.DutyPeriodUncheckedCreateWithoutPharmacyInput> | Prisma.DutyPeriodCreateWithoutPharmacyInput[] | Prisma.DutyPeriodUncheckedCreateWithoutPharmacyInput[]
  connectOrCreate?: Prisma.DutyPeriodCreateOrConnectWithoutPharmacyInput | Prisma.DutyPeriodCreateOrConnectWithoutPharmacyInput[]
  upsert?: Prisma.DutyPeriodUpsertWithWhereUniqueWithoutPharmacyInput | Prisma.DutyPeriodUpsertWithWhereUniqueWithoutPharmacyInput[]
  createMany?: Prisma.DutyPeriodCreateManyPharmacyInputEnvelope
  set?: Prisma.DutyPeriodWhereUniqueInput | Prisma.DutyPeriodWhereUniqueInput[]
  disconnect?: Prisma.DutyPeriodWhereUniqueInput | Prisma.DutyPeriodWhereUniqueInput[]
  delete?: Prisma.DutyPeriodWhereUniqueInput | Prisma.DutyPeriodWhereUniqueInput[]
  connect?: Prisma.DutyPeriodWhereUniqueInput | Prisma.DutyPeriodWhereUniqueInput[]
  update?: Prisma.DutyPeriodUpdateWithWhereUniqueWithoutPharmacyInput | Prisma.DutyPeriodUpdateWithWhereUniqueWithoutPharmacyInput[]
  updateMany?: Prisma.DutyPeriodUpdateManyWithWhereWithoutPharmacyInput | Prisma.DutyPeriodUpdateManyWithWhereWithoutPharmacyInput[]
  deleteMany?: Prisma.DutyPeriodScalarWhereInput | Prisma.DutyPeriodScalarWhereInput[]
}

export type DutyPeriodUncheckedUpdateManyWithoutPharmacyNestedInput = {
  create?: Prisma.XOR<Prisma.DutyPeriodCreateWithoutPharmacyInput, Prisma.DutyPeriodUncheckedCreateWithoutPharmacyInput> | Prisma.DutyPeriodCreateWithoutPharmacyInput[] | Prisma.DutyPeriodUncheckedCreateWithoutPharmacyInput[]
  connectOrCreate?: Prisma.DutyPeriodCreateOrConnectWithoutPharmacyInput | Prisma.DutyPeriodCreateOrConnectWithoutPharmacyInput[]
  upsert?: Prisma.DutyPeriodUpsertWithWhereUniqueWithoutPharmacyInput | Prisma.DutyPeriodUpsertWithWhereUniqueWithoutPharmacyInput[]
  createMany?: Prisma.DutyPeriodCreateManyPharmacyInputEnvelope
  set?: Prisma.DutyPeriodWhereUniqueInput | Prisma.DutyPeriodWhereUniqueInput[]
  disconnect?: Prisma.DutyPeriodWhereUniqueInput | Prisma.DutyPeriodWhereUniqueInput[]
  delete?: Prisma.DutyPeriodWhereUniqueInput | Prisma.DutyPeriodWhereUniqueInput[]
  connect?: Prisma.DutyPeriodWhereUniqueInput | Prisma.DutyPeriodWhereUniqueInput[]
  update?: Prisma.DutyPeriodUpdateWithWhereUniqueWithoutPharmacyInput | Prisma.DutyPeriodUpdateWithWhereUniqueWithoutPharmacyInput[]
  updateMany?: Prisma.DutyPeriodUpdateManyWithWhereWithoutPharmacyInput | Prisma.DutyPeriodUpdateManyWithWhereWithoutPharmacyInput[]
  deleteMany?: Prisma.DutyPeriodScalarWhereInput | Prisma.DutyPeriodScalarWhereInput[]
}

export type DutyPeriodCreateWithoutPharmacyInput = {
  id?: string
  startDate: Date | string
  endDate: Date | string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DutyPeriodUncheckedCreateWithoutPharmacyInput = {
  id?: string
  startDate: Date | string
  endDate: Date | string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DutyPeriodCreateOrConnectWithoutPharmacyInput = {
  where: Prisma.DutyPeriodWhereUniqueInput
  create: Prisma.XOR<Prisma.DutyPeriodCreateWithoutPharmacyInput, Prisma.DutyPeriodUncheckedCreateWithoutPharmacyInput>
}

export type DutyPeriodCreateManyPharmacyInputEnvelope = {
  data: Prisma.DutyPeriodCreateManyPharmacyInput | Prisma.DutyPeriodCreateManyPharmacyInput[]
  skipDuplicates?: boolean
}

export type DutyPeriodUpsertWithWhereUniqueWithoutPharmacyInput = {
  where: Prisma.DutyPeriodWhereUniqueInput
  update: Prisma.XOR<Prisma.DutyPeriodUpdateWithoutPharmacyInput, Prisma.DutyPeriodUncheckedUpdateWithoutPharmacyInput>
  create: Prisma.XOR<Prisma.DutyPeriodCreateWithoutPharmacyInput, Prisma.DutyPeriodUncheckedCreateWithoutPharmacyInput>
}

export type DutyPeriodUpdateWithWhereUniqueWithoutPharmacyInput = {
  where: Prisma.DutyPeriodWhereUniqueInput
  data: Prisma.XOR<Prisma.DutyPeriodUpdateWithoutPharmacyInput, Prisma.DutyPeriodUncheckedUpdateWithoutPharmacyInput>
}

export type DutyPeriodUpdateManyWithWhereWithoutPharmacyInput = {
  where: Prisma.DutyPeriodScalarWhereInput
  data: Prisma.XOR<Prisma.DutyPeriodUpdateManyMutationInput, Prisma.DutyPeriodUncheckedUpdateManyWithoutPharmacyInput>
}

export type DutyPeriodScalarWhereInput = {
  AND?: Prisma.DutyPeriodScalarWhereInput | Prisma.DutyPeriodScalarWhereInput[]
  OR?: Prisma.DutyPeriodScalarWhereInput[]
  NOT?: Prisma.DutyPeriodScalarWhereInput | Prisma.DutyPeriodScalarWhereInput[]
  id?: Prisma.StringFilter<"DutyPeriod"> | string
  startDate?: Prisma.DateTimeFilter<"DutyPeriod"> | Date | string
  endDate?: Prisma.DateTimeFilter<"DutyPeriod"> | Date | string
  notes?: Prisma.StringNullableFilter<"DutyPeriod"> | string | null
  createdAt?: Prisma.DateTimeFilter<"DutyPeriod"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DutyPeriod"> | Date | string
  pharmacyId?: Prisma.StringFilter<"DutyPeriod"> | string
}

export type DutyPeriodCreateManyPharmacyInput = {
  id?: string
  startDate: Date | string
  endDate: Date | string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DutyPeriodUpdateWithoutPharmacyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DutyPeriodUncheckedUpdateWithoutPharmacyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DutyPeriodUncheckedUpdateManyWithoutPharmacyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type DutyPeriodSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  startDate?: boolean
  endDate?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  pharmacyId?: boolean
  pharmacy?: boolean | Prisma.PharmacyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dutyPeriod"]>

export type DutyPeriodSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  startDate?: boolean
  endDate?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  pharmacyId?: boolean
  pharmacy?: boolean | Prisma.PharmacyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dutyPeriod"]>

export type DutyPeriodSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  startDate?: boolean
  endDate?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  pharmacyId?: boolean
  pharmacy?: boolean | Prisma.PharmacyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dutyPeriod"]>

export type DutyPeriodSelectScalar = {
  id?: boolean
  startDate?: boolean
  endDate?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  pharmacyId?: boolean
}

export type DutyPeriodOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "startDate" | "endDate" | "notes" | "createdAt" | "updatedAt" | "pharmacyId", ExtArgs["result"]["dutyPeriod"]>
export type DutyPeriodInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pharmacy?: boolean | Prisma.PharmacyDefaultArgs<ExtArgs>
}
export type DutyPeriodIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pharmacy?: boolean | Prisma.PharmacyDefaultArgs<ExtArgs>
}
export type DutyPeriodIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pharmacy?: boolean | Prisma.PharmacyDefaultArgs<ExtArgs>
}

export type $DutyPeriodPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DutyPeriod"
  objects: {
    pharmacy: Prisma.$PharmacyPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    startDate: Date
    endDate: Date
    notes: string | null
    createdAt: Date
    updatedAt: Date
    pharmacyId: string
  }, ExtArgs["result"]["dutyPeriod"]>
  composites: {}
}

export type DutyPeriodGetPayload<S extends boolean | null | undefined | DutyPeriodDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DutyPeriodPayload, S>

export type DutyPeriodCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DutyPeriodFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DutyPeriodCountAggregateInputType | true
  }

export interface DutyPeriodDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DutyPeriod'], meta: { name: 'DutyPeriod' } }
  /**
   * Find zero or one DutyPeriod that matches the filter.
   * @param {DutyPeriodFindUniqueArgs} args - Arguments to find a DutyPeriod
   * @example
   * // Get one DutyPeriod
   * const dutyPeriod = await prisma.dutyPeriod.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DutyPeriodFindUniqueArgs>(args: Prisma.SelectSubset<T, DutyPeriodFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DutyPeriodClient<runtime.Types.Result.GetResult<Prisma.$DutyPeriodPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DutyPeriod that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DutyPeriodFindUniqueOrThrowArgs} args - Arguments to find a DutyPeriod
   * @example
   * // Get one DutyPeriod
   * const dutyPeriod = await prisma.dutyPeriod.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DutyPeriodFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DutyPeriodFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DutyPeriodClient<runtime.Types.Result.GetResult<Prisma.$DutyPeriodPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DutyPeriod that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyPeriodFindFirstArgs} args - Arguments to find a DutyPeriod
   * @example
   * // Get one DutyPeriod
   * const dutyPeriod = await prisma.dutyPeriod.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DutyPeriodFindFirstArgs>(args?: Prisma.SelectSubset<T, DutyPeriodFindFirstArgs<ExtArgs>>): Prisma.Prisma__DutyPeriodClient<runtime.Types.Result.GetResult<Prisma.$DutyPeriodPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DutyPeriod that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyPeriodFindFirstOrThrowArgs} args - Arguments to find a DutyPeriod
   * @example
   * // Get one DutyPeriod
   * const dutyPeriod = await prisma.dutyPeriod.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DutyPeriodFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DutyPeriodFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DutyPeriodClient<runtime.Types.Result.GetResult<Prisma.$DutyPeriodPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DutyPeriods that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyPeriodFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DutyPeriods
   * const dutyPeriods = await prisma.dutyPeriod.findMany()
   * 
   * // Get first 10 DutyPeriods
   * const dutyPeriods = await prisma.dutyPeriod.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dutyPeriodWithIdOnly = await prisma.dutyPeriod.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DutyPeriodFindManyArgs>(args?: Prisma.SelectSubset<T, DutyPeriodFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DutyPeriodPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DutyPeriod.
   * @param {DutyPeriodCreateArgs} args - Arguments to create a DutyPeriod.
   * @example
   * // Create one DutyPeriod
   * const DutyPeriod = await prisma.dutyPeriod.create({
   *   data: {
   *     // ... data to create a DutyPeriod
   *   }
   * })
   * 
   */
  create<T extends DutyPeriodCreateArgs>(args: Prisma.SelectSubset<T, DutyPeriodCreateArgs<ExtArgs>>): Prisma.Prisma__DutyPeriodClient<runtime.Types.Result.GetResult<Prisma.$DutyPeriodPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DutyPeriods.
   * @param {DutyPeriodCreateManyArgs} args - Arguments to create many DutyPeriods.
   * @example
   * // Create many DutyPeriods
   * const dutyPeriod = await prisma.dutyPeriod.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DutyPeriodCreateManyArgs>(args?: Prisma.SelectSubset<T, DutyPeriodCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DutyPeriods and returns the data saved in the database.
   * @param {DutyPeriodCreateManyAndReturnArgs} args - Arguments to create many DutyPeriods.
   * @example
   * // Create many DutyPeriods
   * const dutyPeriod = await prisma.dutyPeriod.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DutyPeriods and only return the `id`
   * const dutyPeriodWithIdOnly = await prisma.dutyPeriod.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DutyPeriodCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DutyPeriodCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DutyPeriodPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DutyPeriod.
   * @param {DutyPeriodDeleteArgs} args - Arguments to delete one DutyPeriod.
   * @example
   * // Delete one DutyPeriod
   * const DutyPeriod = await prisma.dutyPeriod.delete({
   *   where: {
   *     // ... filter to delete one DutyPeriod
   *   }
   * })
   * 
   */
  delete<T extends DutyPeriodDeleteArgs>(args: Prisma.SelectSubset<T, DutyPeriodDeleteArgs<ExtArgs>>): Prisma.Prisma__DutyPeriodClient<runtime.Types.Result.GetResult<Prisma.$DutyPeriodPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DutyPeriod.
   * @param {DutyPeriodUpdateArgs} args - Arguments to update one DutyPeriod.
   * @example
   * // Update one DutyPeriod
   * const dutyPeriod = await prisma.dutyPeriod.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DutyPeriodUpdateArgs>(args: Prisma.SelectSubset<T, DutyPeriodUpdateArgs<ExtArgs>>): Prisma.Prisma__DutyPeriodClient<runtime.Types.Result.GetResult<Prisma.$DutyPeriodPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DutyPeriods.
   * @param {DutyPeriodDeleteManyArgs} args - Arguments to filter DutyPeriods to delete.
   * @example
   * // Delete a few DutyPeriods
   * const { count } = await prisma.dutyPeriod.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DutyPeriodDeleteManyArgs>(args?: Prisma.SelectSubset<T, DutyPeriodDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DutyPeriods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyPeriodUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DutyPeriods
   * const dutyPeriod = await prisma.dutyPeriod.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DutyPeriodUpdateManyArgs>(args: Prisma.SelectSubset<T, DutyPeriodUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DutyPeriods and returns the data updated in the database.
   * @param {DutyPeriodUpdateManyAndReturnArgs} args - Arguments to update many DutyPeriods.
   * @example
   * // Update many DutyPeriods
   * const dutyPeriod = await prisma.dutyPeriod.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DutyPeriods and only return the `id`
   * const dutyPeriodWithIdOnly = await prisma.dutyPeriod.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DutyPeriodUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DutyPeriodUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DutyPeriodPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DutyPeriod.
   * @param {DutyPeriodUpsertArgs} args - Arguments to update or create a DutyPeriod.
   * @example
   * // Update or create a DutyPeriod
   * const dutyPeriod = await prisma.dutyPeriod.upsert({
   *   create: {
   *     // ... data to create a DutyPeriod
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DutyPeriod we want to update
   *   }
   * })
   */
  upsert<T extends DutyPeriodUpsertArgs>(args: Prisma.SelectSubset<T, DutyPeriodUpsertArgs<ExtArgs>>): Prisma.Prisma__DutyPeriodClient<runtime.Types.Result.GetResult<Prisma.$DutyPeriodPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DutyPeriods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyPeriodCountArgs} args - Arguments to filter DutyPeriods to count.
   * @example
   * // Count the number of DutyPeriods
   * const count = await prisma.dutyPeriod.count({
   *   where: {
   *     // ... the filter for the DutyPeriods we want to count
   *   }
   * })
  **/
  count<T extends DutyPeriodCountArgs>(
    args?: Prisma.Subset<T, DutyPeriodCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DutyPeriodCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DutyPeriod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyPeriodAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DutyPeriodAggregateArgs>(args: Prisma.Subset<T, DutyPeriodAggregateArgs>): Prisma.PrismaPromise<GetDutyPeriodAggregateType<T>>

  /**
   * Group by DutyPeriod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DutyPeriodGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DutyPeriodGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DutyPeriodGroupByArgs['orderBy'] }
      : { orderBy?: DutyPeriodGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DutyPeriodGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDutyPeriodGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DutyPeriod model
 */
readonly fields: DutyPeriodFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DutyPeriod.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DutyPeriodClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  pharmacy<T extends Prisma.PharmacyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PharmacyDefaultArgs<ExtArgs>>): Prisma.Prisma__PharmacyClient<runtime.Types.Result.GetResult<Prisma.$PharmacyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DutyPeriod model
 */
export interface DutyPeriodFieldRefs {
  readonly id: Prisma.FieldRef<"DutyPeriod", 'String'>
  readonly startDate: Prisma.FieldRef<"DutyPeriod", 'DateTime'>
  readonly endDate: Prisma.FieldRef<"DutyPeriod", 'DateTime'>
  readonly notes: Prisma.FieldRef<"DutyPeriod", 'String'>
  readonly createdAt: Prisma.FieldRef<"DutyPeriod", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"DutyPeriod", 'DateTime'>
  readonly pharmacyId: Prisma.FieldRef<"DutyPeriod", 'String'>
}
    

// Custom InputTypes
/**
 * DutyPeriod findUnique
 */
export type DutyPeriodFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutyPeriod
   */
  select?: Prisma.DutyPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutyPeriod
   */
  omit?: Prisma.DutyPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DutyPeriodInclude<ExtArgs> | null
  /**
   * Filter, which DutyPeriod to fetch.
   */
  where: Prisma.DutyPeriodWhereUniqueInput
}

/**
 * DutyPeriod findUniqueOrThrow
 */
export type DutyPeriodFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutyPeriod
   */
  select?: Prisma.DutyPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutyPeriod
   */
  omit?: Prisma.DutyPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DutyPeriodInclude<ExtArgs> | null
  /**
   * Filter, which DutyPeriod to fetch.
   */
  where: Prisma.DutyPeriodWhereUniqueInput
}

/**
 * DutyPeriod findFirst
 */
export type DutyPeriodFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutyPeriod
   */
  select?: Prisma.DutyPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutyPeriod
   */
  omit?: Prisma.DutyPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DutyPeriodInclude<ExtArgs> | null
  /**
   * Filter, which DutyPeriod to fetch.
   */
  where?: Prisma.DutyPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DutyPeriods to fetch.
   */
  orderBy?: Prisma.DutyPeriodOrderByWithRelationInput | Prisma.DutyPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DutyPeriods.
   */
  cursor?: Prisma.DutyPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DutyPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DutyPeriods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DutyPeriods.
   */
  distinct?: Prisma.DutyPeriodScalarFieldEnum | Prisma.DutyPeriodScalarFieldEnum[]
}

/**
 * DutyPeriod findFirstOrThrow
 */
export type DutyPeriodFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutyPeriod
   */
  select?: Prisma.DutyPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutyPeriod
   */
  omit?: Prisma.DutyPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DutyPeriodInclude<ExtArgs> | null
  /**
   * Filter, which DutyPeriod to fetch.
   */
  where?: Prisma.DutyPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DutyPeriods to fetch.
   */
  orderBy?: Prisma.DutyPeriodOrderByWithRelationInput | Prisma.DutyPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DutyPeriods.
   */
  cursor?: Prisma.DutyPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DutyPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DutyPeriods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DutyPeriods.
   */
  distinct?: Prisma.DutyPeriodScalarFieldEnum | Prisma.DutyPeriodScalarFieldEnum[]
}

/**
 * DutyPeriod findMany
 */
export type DutyPeriodFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutyPeriod
   */
  select?: Prisma.DutyPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutyPeriod
   */
  omit?: Prisma.DutyPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DutyPeriodInclude<ExtArgs> | null
  /**
   * Filter, which DutyPeriods to fetch.
   */
  where?: Prisma.DutyPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DutyPeriods to fetch.
   */
  orderBy?: Prisma.DutyPeriodOrderByWithRelationInput | Prisma.DutyPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DutyPeriods.
   */
  cursor?: Prisma.DutyPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DutyPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DutyPeriods.
   */
  skip?: number
  distinct?: Prisma.DutyPeriodScalarFieldEnum | Prisma.DutyPeriodScalarFieldEnum[]
}

/**
 * DutyPeriod create
 */
export type DutyPeriodCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutyPeriod
   */
  select?: Prisma.DutyPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutyPeriod
   */
  omit?: Prisma.DutyPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DutyPeriodInclude<ExtArgs> | null
  /**
   * The data needed to create a DutyPeriod.
   */
  data: Prisma.XOR<Prisma.DutyPeriodCreateInput, Prisma.DutyPeriodUncheckedCreateInput>
}

/**
 * DutyPeriod createMany
 */
export type DutyPeriodCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DutyPeriods.
   */
  data: Prisma.DutyPeriodCreateManyInput | Prisma.DutyPeriodCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DutyPeriod createManyAndReturn
 */
export type DutyPeriodCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutyPeriod
   */
  select?: Prisma.DutyPeriodSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DutyPeriod
   */
  omit?: Prisma.DutyPeriodOmit<ExtArgs> | null
  /**
   * The data used to create many DutyPeriods.
   */
  data: Prisma.DutyPeriodCreateManyInput | Prisma.DutyPeriodCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DutyPeriodIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DutyPeriod update
 */
export type DutyPeriodUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutyPeriod
   */
  select?: Prisma.DutyPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutyPeriod
   */
  omit?: Prisma.DutyPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DutyPeriodInclude<ExtArgs> | null
  /**
   * The data needed to update a DutyPeriod.
   */
  data: Prisma.XOR<Prisma.DutyPeriodUpdateInput, Prisma.DutyPeriodUncheckedUpdateInput>
  /**
   * Choose, which DutyPeriod to update.
   */
  where: Prisma.DutyPeriodWhereUniqueInput
}

/**
 * DutyPeriod updateMany
 */
export type DutyPeriodUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DutyPeriods.
   */
  data: Prisma.XOR<Prisma.DutyPeriodUpdateManyMutationInput, Prisma.DutyPeriodUncheckedUpdateManyInput>
  /**
   * Filter which DutyPeriods to update
   */
  where?: Prisma.DutyPeriodWhereInput
  /**
   * Limit how many DutyPeriods to update.
   */
  limit?: number
}

/**
 * DutyPeriod updateManyAndReturn
 */
export type DutyPeriodUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutyPeriod
   */
  select?: Prisma.DutyPeriodSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DutyPeriod
   */
  omit?: Prisma.DutyPeriodOmit<ExtArgs> | null
  /**
   * The data used to update DutyPeriods.
   */
  data: Prisma.XOR<Prisma.DutyPeriodUpdateManyMutationInput, Prisma.DutyPeriodUncheckedUpdateManyInput>
  /**
   * Filter which DutyPeriods to update
   */
  where?: Prisma.DutyPeriodWhereInput
  /**
   * Limit how many DutyPeriods to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DutyPeriodIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DutyPeriod upsert
 */
export type DutyPeriodUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutyPeriod
   */
  select?: Prisma.DutyPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutyPeriod
   */
  omit?: Prisma.DutyPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DutyPeriodInclude<ExtArgs> | null
  /**
   * The filter to search for the DutyPeriod to update in case it exists.
   */
  where: Prisma.DutyPeriodWhereUniqueInput
  /**
   * In case the DutyPeriod found by the `where` argument doesn't exist, create a new DutyPeriod with this data.
   */
  create: Prisma.XOR<Prisma.DutyPeriodCreateInput, Prisma.DutyPeriodUncheckedCreateInput>
  /**
   * In case the DutyPeriod was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DutyPeriodUpdateInput, Prisma.DutyPeriodUncheckedUpdateInput>
}

/**
 * DutyPeriod delete
 */
export type DutyPeriodDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutyPeriod
   */
  select?: Prisma.DutyPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutyPeriod
   */
  omit?: Prisma.DutyPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DutyPeriodInclude<ExtArgs> | null
  /**
   * Filter which DutyPeriod to delete.
   */
  where: Prisma.DutyPeriodWhereUniqueInput
}

/**
 * DutyPeriod deleteMany
 */
export type DutyPeriodDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DutyPeriods to delete
   */
  where?: Prisma.DutyPeriodWhereInput
  /**
   * Limit how many DutyPeriods to delete.
   */
  limit?: number
}

/**
 * DutyPeriod without action
 */
export type DutyPeriodDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DutyPeriod
   */
  select?: Prisma.DutyPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DutyPeriod
   */
  omit?: Prisma.DutyPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DutyPeriodInclude<ExtArgs> | null
}
